random_seed: 42

data:
  external_data_paths: # Paths to the .mat files provided by Severson et. al.
    - /home/gabriel/data/severson/raw/2017-05-12_batchdata_updated_struct_errorcorrect.mat 
    - /home/gabriel/data/severson/raw/2017-06-30_batchdata_updated_struct_errorcorrect.mat
    - /home/gabriel/data/severson/raw/2018-04-12_batchdata_updated_struct_errorcorrect.mat
  loaded_data_path: ./data/external/cells_data.h5
  min_cycle_length: 100 # number of samples
  max_cycle_length: 6000 # number of samples
  cells_rated_capacity: 1.1 # Ah
  margin_for_upper_capacity_bound: 1.2
  time_jump_threshold: 400 # sec
  target_frequency: 1 # Hz
  processed_cells_data_folder: ./data/processed/cells
  eol_definition: 80 # SoH
  features_data_path: ./data/interim/features.parquet
  train_cells_proportion: 0.8
  features_process_window_size: 10
  features_process_savgol_order: 1
  train_data_path: ./data/interim/train_df.parquet
  test_data_path: ./data/interim/test_df.parquet

modeling:
  optimization_subset_frac: 0.1 # Proportion of the train data used to optimize hyperparams
  target: SOH
  num_features: 8
  n_jobs: 4 # Available core for models training
  feature_importances_dir: ./models/feature_importances/
  max_trials: 50
  early_stopping_patience: 10
  optimization_results_dir: ./models/optimization/
  evaluation_results_dir: ./models/evaluation/

analysis:
  figures_folder: ./reports/figures
  example_cell: b1c14

defaults:
  - _self_
  - model: tweedie
  - override hydra/launcher: joblib
  
hydra:
  launcher:
    n_jobs: 4 # Concurrency of Hydra runs
  sweeper:
    params:
      model: lightgbm,tweedie,knn
      modeling.target: SOH,RUL
      modeling.num_features: 4,8,12,16